import 'package:pusdatin_end/models/mock/models_dataBarang.dart';

// Dummy data untuk barang
List<dataBarang> dummyItems = [
  dataBarang(
      idBarang: 'FNTR.1750.WOD',
      nmBarang: 'Emerald',
      mrkBarang: 'Gems',
      pngBarang: 'Cave',
      lssBarang: 2,
      tglMasuk: DateTime(2019, 9, 8),
      jmlBarang: 12,
      kondisi: 'Baik',
      imgBarang: 'assets/images/drone.png'),
  dataBarang(
      idBarang: 'FNTR.1890.HWD',
      nmBarang: 'Aquamarine',
      mrkBarang: 'Gems',
      pngBarang: 'SkullCave',
      lssBarang: 3,
      tglMasuk: DateTime(2019, 9, 7),
      jmlBarang: 11,
      kondisi: 'Rusak Ringan',
      imgBarang: 'assets/images/drone2.png'),
  dataBarang(
      idBarang: 'FNTR.1785.HWD',
      nmBarang: 'Tigerseye',
      mrkBarang: 'Geode',
      pngBarang: 'Cave',
      lssBarang: 3,
      tglMasuk: DateTime(2019, 7, 7),
      jmlBarang: 15,
      kondisi: 'Baik',
      imgBarang: 'assets/images/drone.png'),
  dataBarang(
      idBarang: 'FNTR.1787.WOD',
      nmBarang: 'Bixite',
      mrkBarang: 'Artisan',
      pngBarang: 'SkullCave',
      lssBarang: 3,
      tglMasuk: DateTime(2019, 7, 6),
      jmlBarang: 19,
      kondisi: 'Rusak Berat',
      imgBarang: 'assets/images/drone3.png'),
  dataBarang(
      idBarang: 'FNTR.1680.HWD',
      nmBarang: 'Aerinite',
      mrkBarang: 'Artisan',
      pngBarang: 'Cave',
      lssBarang: 2,
      tglMasuk: DateTime(2019, 7, 19),
      jmlBarang: 16,
      kondisi: 'Rusak Ringan',
      imgBarang: 'assets/images/drone4.png'),
];
